# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actiontext/all/actiontext.rbi
#
# actiontext-8.0.2.1

module ActionText
  def self.deprecator; end
  def self.gem_version; end
  def self.html_document_class; end
  def self.html_document_fragment_class; end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
  def self.version; end
  extend ActiveSupport::Autoload
end
module ActionText::VERSION
end
module ActionText::Attachables
  extend ActiveSupport::Autoload
end
module ActionText::Attachments
  extend ActiveSupport::Autoload
end
class ActionText::Engine < Rails::Engine
end
module ActionText::Attachable
  def attachable_content_type; end
  def attachable_filename; end
  def attachable_filesize; end
  def attachable_metadata; end
  def attachable_sgid; end
  def attribute_names_for_serialization; end
  def previewable_attachable?; end
  def read_attribute_for_serialization(key); end
  def self.attachable_from_sgid(sgid); end
  def self.from_attachable_sgid(sgid, options = nil); end
  def self.from_node(node); end
  def to_attachable_partial_path; end
  def to_rich_text_attributes(attributes = nil); end
  def to_trix_content_attachment_partial_path; end
  extend ActiveSupport::Concern
end
module ActionText::Attachable::ClassMethods
  def from_attachable_sgid(sgid); end
  def to_missing_attachable_partial_path; end
end
class ActionText::Attachables::ContentAttachment
  def __callbacks; end
  def _run_validate_callbacks(&block); end
  def _validate_callbacks; end
  def _validators; end
  def _validators?; end
  def attachable_plain_text_representation(caption); end
  def content; end
  def content=(arg0); end
  def content_instance; end
  def content_type; end
  def content_type=(arg0); end
  def model_name(&); end
  def param_delimiter=(arg0); end
  def self.__callbacks; end
  def self.__callbacks=(value); end
  def self.__class_attr___callbacks; end
  def self.__class_attr___callbacks=(new_value); end
  def self.__class_attr__validators; end
  def self.__class_attr__validators=(new_value); end
  def self.__class_attr_param_delimiter; end
  def self.__class_attr_param_delimiter=(new_value); end
  def self._validate_callbacks; end
  def self._validate_callbacks=(value); end
  def self._validators; end
  def self._validators=(value); end
  def self._validators?; end
  def self.from_node(node); end
  def self.param_delimiter; end
  def self.param_delimiter=(value); end
  def self.param_delimiter?; end
  def to_html; end
  def to_partial_path; end
  def to_s; end
  extend ActiveModel::Callbacks
  extend ActiveModel::Conversion::ClassMethods
  extend ActiveModel::Naming
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  extend ActiveModel::Translation
  extend ActiveModel::Validations::ClassMethods
  extend ActiveModel::Validations::HelperMethods
  extend ActiveSupport::Callbacks::ClassMethods
  extend ActiveSupport::DescendantsTracker
  include ActiveModel::API
  include ActiveModel::Conversion
  include ActiveModel::Model
  include ActiveModel::Validations
  include ActiveModel::Validations::HelperMethods
  include ActiveSupport::Callbacks
end
class ActionText::Attachables::MissingAttachable
  def initialize(sgid); end
  def model; end
  def model_name(&); end
  def to_partial_path; end
  extend ActiveModel::Naming
end
class ActionText::Attachables::RemoteImage
  def attachable_plain_text_representation(caption); end
  def content_type; end
  def height; end
  def initialize(attributes = nil); end
  def model_name(&); end
  def self.attributes_from_node(node); end
  def self.content_type_is_image?(content_type); end
  def self.from_node(node); end
  def to_partial_path; end
  def url; end
  def width; end
  extend ActiveModel::Naming
end
class ActionText::AttachmentGallery
  def __callbacks; end
  def _run_validate_callbacks(&block); end
  def _validate_callbacks; end
  def _validators; end
  def _validators?; end
  def attachments; end
  def initialize(node); end
  def inspect; end
  def model_name(&); end
  def node; end
  def param_delimiter=(arg0); end
  def self.__callbacks; end
  def self.__callbacks=(value); end
  def self.__class_attr___callbacks; end
  def self.__class_attr___callbacks=(new_value); end
  def self.__class_attr__validators; end
  def self.__class_attr__validators=(new_value); end
  def self.__class_attr_param_delimiter; end
  def self.__class_attr_param_delimiter=(new_value); end
  def self._validate_callbacks; end
  def self._validate_callbacks=(value); end
  def self._validators; end
  def self._validators=(value); end
  def self._validators?; end
  def self.attachment_selector; end
  def self.find_attachment_gallery_nodes(content); end
  def self.fragment_by_canonicalizing_attachment_galleries(content); end
  def self.fragment_by_replacing_attachment_gallery_nodes(content); end
  def self.from_node(node); end
  def self.param_delimiter; end
  def self.param_delimiter=(value); end
  def self.param_delimiter?; end
  def self.selector; end
  def size; end
  extend ActiveModel::Callbacks
  extend ActiveModel::Conversion::ClassMethods
  extend ActiveModel::Naming
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  extend ActiveModel::Translation
  extend ActiveModel::Validations::ClassMethods
  extend ActiveModel::Validations::HelperMethods
  extend ActiveSupport::Callbacks::ClassMethods
  extend ActiveSupport::DescendantsTracker
  include ActiveModel::API
  include ActiveModel::Conversion
  include ActiveModel::Model
  include ActiveModel::Validations
  include ActiveModel::Validations::HelperMethods
  include ActiveSupport::Callbacks
end
module ActionText::Attachments::TrixConversion
  def to_trix_attachment(content = nil); end
  def trix_attachment_content; end
  extend ActiveSupport::Concern
end
module ActionText::Attachments::TrixConversion::ClassMethods
  def fragment_by_converting_trix_attachments(content); end
  def from_trix_attachment(trix_attachment); end
end
module ActionText::Attachments::Minification
  extend ActiveSupport::Concern
end
module ActionText::Attachments::Minification::ClassMethods
  def fragment_by_minifying_attachments(content); end
end
module ActionText::Attachments::Caching
  def cache_digest; end
  def cache_key(*args); end
end
class ActionText::Attachment
  def attachable; end
  def attachable_attributes; end
  def caption; end
  def full_attributes; end
  def initialize(node, attachable); end
  def inspect; end
  def method_missing(method, *, **, &); end
  def node; end
  def node_attributes; end
  def respond_to_missing?(name, include_private = nil); end
  def self.fragment_by_canonicalizing_attachments(content); end
  def self.from_attachable(attachable, attributes = nil); end
  def self.from_attachables(attachables); end
  def self.from_attributes(attributes, attachable = nil); end
  def self.from_node(node, attachable = nil); end
  def self.node_from_attributes(attributes); end
  def self.process_attributes(attributes); end
  def self.tag_name; end
  def self.tag_name=(val); end
  def sgid_attributes; end
  def tag_name; end
  def tag_name=(val); end
  def to_html; end
  def to_param(*, **, &); end
  def to_plain_text; end
  def to_s; end
  def with_full_attributes; end
  extend ActionText::Attachments::Minification::ClassMethods
  extend ActionText::Attachments::TrixConversion::ClassMethods
  include ActionText::Attachments::TrixConversion
end
module ActionText::Attribute
  extend ActiveSupport::Concern
end
module ActionText::Attribute::ClassMethods
  def has_rich_text(name, encrypted: nil, strict_loading: nil, store_if_blank: nil); end
  def rich_text_association_names; end
  def with_all_rich_text; end
end
module ActionText::Rendering
  extend ActiveSupport::Concern
end
module ActionText::Rendering::ClassMethods
  def action_controller_renderer; end
  def render(*args, &block); end
  def with_renderer(renderer); end
end
module ActionText::Serialization
  def _dump(*); end
  extend ActiveSupport::Concern
end
module ActionText::Serialization::ClassMethods
  def _load(content); end
  def dump(content); end
  def load(content); end
end
class ActionText::Content
end
